---
{{- $productGroupId := toString .Values.fyre.credentials.productGroupId -}}
apiVersion: v1
kind: Secret
metadata:
  name: fyre-{{ .Values.fyre.credentials.user }}-secret
  namespace: {{ default "default" .Release.Namespace }}
data:
  username: "{{ b64enc .Values.fyre.credentials.user }}"
  password: "{{ b64enc .Values.fyre.credentials.token }}"
  product_group_id: "{{ b64enc $productGroupId }}"
type: Opaque
