{{- if .Values.cp4waiops.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cp4waiops
spec:
  generators:
  {{- if .Values.argocd.allowLocalDeploy }}
  - clusters: {}
  {{- else }}
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}-cp4waiops` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "200"
    spec:
      destination:
        namespace: '{{ .Values.cp4waiops.namespace }}'
        server: '{{ `{{server}}` }}'
      project: default
      source:
        path: {{ template "cp4waiops.configPath" . }}
        repoURL: https://github.com/morningspace/cp4waiops-sandbox
        targetRevision: dev
        helm:
          valueFiles:
            - values.yaml
          {{- if eq .Values.cp4waiops.profile "x-small" }}
            - values.x-small.yaml
          {{- end }}
          {{- if eq .Values.cp4waiops.version "custom-build" }}
            - values.custom-build.yaml
          {{- end }}
          parameters:
            - name: {{ template "cp4waiops.chartName" . }}.spec.dockerUsername
              value: '{{ .Values.cp4waiops.dockerUsername }}'
            - name: {{ template "cp4waiops.chartName" . }}.spec.dockerPassword
              value: '{{ .Values.cp4waiops.dockerPassword }}'
            - name: {{ template "cp4waiops.chartName" . }}.spec.aiManager.instanceName
              value: '{{ .Values.cp4waiops.aimanager.instanceName }}'
            - name: {{ template "cp4waiops.chartName" . }}.spec.aiManager.namespace
              value: '{{ .Values.cp4waiops.aimanager.namespace }}'
            {{- if eq .Values.cp4waiops.profile "x-small" }}
            - name: {{ template "cp4waiops.chartName" . }}.spec.aiManager.size
              value: 'small'
            {{- else }}
            - name: {{ template "cp4waiops.chartName" . }}.spec.aiManager.size
              value: '{{ .Values.cp4waiops.profile }}'
            {{- end }}
      ignoreDifferences:
        - group: orchestrator.aiops.ibm.com
          jsonPointers:
            - /spec/pakModules
          kind: Installation
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
{{- end }}
